### ISSUE TITLE
On dropping several files, if one file fails the validation, the whole bunch fails

### ISSUE THREAD

**Issue by 2treesinmyears** [ZouYouShun/ngxf-uploader#1]
Can you add parameter to continue upload, skipping the invalid files?

**Comment by ZouYouShun** [comment]
I am sorry to respond so late. I has add this skip parameter with FileOption.

When you set `skipInvalid: true`, the error file will be ignored, and return the pass file array.

### FileOption
```ts
export interface FileOption {
  // file accept size
  size?: { min?: number, max?: number }; // unit: Byte,
  // deafultis false, when you want to skip the Invalid file, you can set it to true
  skipInvalid?: boolean;
}
```

You can see detial from here.
https://alanzouhome.firebaseapp.com/package/NgxfUploader
