### ISSUE TITLE
ngxf-uploader在window7 ie浏览器不兼容。Ngxf-uploader is not compatible with Windows 7 ie

### ISSUE THREAD

**Issue by LningCode** [ZouYouShun/ngxf-uploader#3]
Ngxf-uploader is not compatible in Windows 7 ie, and clicking the upload button does not respond

**Comment by ZouYouShun** [comment]
Hi @LningCode, which ie version you use? is ie11? angular2+ must be work with ie11+

Can you open the console to take a screen shot, let me know what issue occur.

**Comment by ZouYouShun** [comment]
Hi @LningCode, I fix the problem with ie

## 1.5.1

### Fix problem with IE

* **Append upload input elm on body:** IE need actual element on document, that can occur upload change event.

* **Change peerDependencies to more than 6.0.0:** Change peerDependencies to more than 6.0.0
