### ISSUE TITLE
日志输出可控？

### ISSUE THREAD

**Issue by StringKe** [ZouYouShun/ngxf-uploader#8]
是否可以控制 NgxfUploaderService 中 console.log 的输出？

**Comment by ZouYouShun** [comment]
oh! that a mistake....

let me fix let and create a patch release...

thanks guy.

**Comment by ZouYouShun** [comment]
@StringKe thanks for your issue, that bug is fix in 1.7.1-beta.1
https://www.npmjs.com/package/ngxf-uploader


thanks a lot

**Comment by StringKe** [comment]
thx
